"""added last_changed_date

Revision ID: 6fed80e6ce8d
Revises: 920780308f08
Create Date: 2025-10-07 18:30:14.813496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fed80e6ce8d'
down_revision: Union[str, Sequence[str], None] = '920780308f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('last_changed_date', sa.DateTime(), nullable=True))
    op.add_column('drug', sa.Column('last_changed_date', sa.DateTime(), nullable=True))
    op.add_column('formulation_type', sa.Column('last_changed_date', sa.DateTime(), nullable=True))
    op.add_column('unit', sa.Column('last_changed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'last_changed_date')
    op.drop_column('formulation_type', 'last_changed_date')
    op.drop_column('drug', 'last_changed_date')
    op.drop_column('brand', 'last_changed_date')
    # ### end Alembic commands ###
