"""add google_account and verification fields

Revision ID: 870886de8e29
Revises: 22d904a6b6aa
Create Date: 2025-11-04 23:44:29.018341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870886de8e29'
down_revision: Union[str, Sequence[str], None] = '22d904a6b6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_google_account', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('password_reset_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_code')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_google_account')
    # ### end Alembic commands ###
