"""added Dispense and dispense_item tables, and their relationships

Revision ID: 94fa7a242a46
Revises: 56b9d021e5db
Create Date: 2025-10-22 05:47:32.898900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fa7a242a46'
down_revision: Union[str, Sequence[str], None] = '56b9d021e5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispense',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispense_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispense_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price_at_dispense', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dispense_id'], ['dispense.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('reorder_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'reorder_level')
    op.drop_table('dispense_item')
    op.drop_table('dispense')
    # ### end Alembic commands ###
